### ISSUE TITLE
Shopify.Webhooks.Registry.process throws error

### ISSUE THREAD

**Issue by mkamalkayani** [Shopify/shopify-api-node#231]
# Issue summary

Sometimes the uninstall webhook route throws an error, and sometimes it works fine. Additionally, the error is misleading, as the uninstall webhook route is getting hit, which means the webhook is registered successfully and it is received by my server. 

`Failed to process webhook: Error: No webhook is registered for topic app/uninstalled`

## Expected behavior

The uninstall webhook should be processed consistently.

## Actual behavior

Inconsistant behavior by the `Shopify.Webhooks.Registry.process(ctx.req, ctx.res)`

## Relavent code

access mode is online.

```js
   const response = await Shopify.Webhooks.Registry.register({
            shop,
            accessToken,
            path: "/webhooks/app_uninstall",
            topic: "APP_UNINSTALLED",
            webhookHandler: async (topic, shop, body) => {
              await sessionStorage.removeShop(shop);
              console.log("app uninstalled", { topic, shop });
            },
          });
```

```js
router.post("/webhooks/app_uninstall", async (ctx) => {
  try {
    await Shopify.Webhooks.Registry.process(ctx.req, ctx.res);
    console.log(`Webhook processed, returned status code 200`);
  } catch (error) {
    console.log(`Failed to process webhook: ${error}`);
  }
});
```

**Comment by arsnl** [comment]
Hi @mkamalkayani ! :) This is a known issue due to the current architecture of the library.

The PR https://github.com/Shopify/shopify-node-api/pull/226 is covering this issue and is currently waiting to be approved by the core team.

Until the PR is merged and pushed on NPM (due to the lack of response from the core team, I think it's gonna take a while...), you can try to apply this hack (https://github.com/Shopify/shopify-node-api/pull/205#issuecomment-888706213).
